import Head from "next/head";
import PostList from "../components/PostList";
import Navbar from "../components/Navbar";
import DetailPost from "../components/DetailPost";
import Footer from "../components/Footer";

export default function Detail() {
  return (
    <div>
      <Head>
        <title>Fast News | Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
      <div className=" bg-primary fixed w-full top-0 z-10">
        <div className="container w-2/3 mx-auto">
          <Navbar />
        </div>
      </div>
      {/* Navbar END */}

      {/* Main */}
      <div className="flex p-10 mt-14 container justify-center mx-auto">
        <div className="p-3 w-1/5 bg-secondary rounded-md shadow-2xl">
          <PostList />
        </div>
        <div className="p-3 ml-5 w-3/5 bg-secondary rounded-md shadow-2xl">
          <DetailPost />
        </div>
      </div>
      {/* Main END */}

      <div className=" bg-primary">
        <div className="container w-2/3 mx-auto">
          <Footer />
        </div>
      </div>
    </div>
  );
}
