import Head from "next/head";
import PostList from "../components/PostList";
import PostHead from "../components/PostHead";
import PostPhoto from "../components/PostPhoto";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fast News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
      <div className=" bg-primary">
        <div className="container w-2/3 mx-auto">
          <Navbar />
        </div>
      </div>
      {/* Navbar END */}

      {/* Main */}
      <div className="flex p-10 container justify-center mx-auto">
        <div className="p-3 w-1/5 bg-secondary rounded-md">
          <PostList />
        </div>
        <div className="ml-3 w-3/5 ">
          <div className="p-3 bg-secondary rounded-md">
            <PostHead />
          </div>
          <div className="p-3 mt-5 bg-secondary rounded-md">
            <PostPhoto />
          </div>
        </div>
      </div>
      {/* Main END */}
    </div>
  );
}
