import Head from "next/head";
import PostList from "../components/PostList";
import PostHead from "../components/PostHead";
import PostPhoto from "../components/PostPhoto";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fast News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
      <div className=" bg-primary fixed w-full top-0 z-10 shadow-xl">
        <div className="container w-4/5 2xl:w-2/3 mx-auto">
          <Navbar />
        </div>
      </div>
      {/* Navbar END */}

      {/* Main */}
      <div className="flex p-10 mt-14 container justify-center mx-auto">
        <div className="p-3 w-60 2xl:w-1/5 bg-secondary rounded-md shadow-2xl">
          <PostList />
        </div>
        <div className="ml-5 w-3/5 ">
          <div className="p-3 bg-secondary rounded-md shadow-2xl">
            <PostHead />
          </div>
          <div className="p-3 mt-5 bg-secondary rounded-md shadow-2xl">
            <PostPhoto />
          </div>
        </div>
      </div>
      {/* Main END */}

      <div className=" bg-primary">
        <div className="container w-2/3 mx-auto">
          <Footer />
        </div>
      </div>
    </div>
  );
}
