import Head from "next/head";
import Navbar from "../components/Navbar";
import UserPage from "../components/UserPage";
import Footer from "../components/Footer";

export default function Detail() {
  return (
    <div>
      <Head>
        <title>Fast News | User Pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
      <div className="bg-primary fixed w-full top-0 z-10">
        <div className="container w-4/5 2xl:w-2/3 mx-auto">
          <Navbar />
        </div>
      </div>
      {/* Navbar END */}

      {/* Main */}
      <div className="flex p-10 mt-14 justify-center">
        <div className="flex-initial p-3 bg-secondary rounded-md shadow-2xl">
          <UserPage />
        </div>
      </div>
      {/* Main END */}

      <div className=" bg-primary">
        <div className="container w-2/3 mx-auto">
          <Footer />
        </div>
      </div>
    </div>
  );
}
